version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - my-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - my-network

  database:
    container_name: db-mysql
    image: mysql:latest
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tariff
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - my-network

networks:
  my-network:
