version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
    entrypoint: [ "/bin/sh", "-c", "/bin/startup.sh" ]
    networks:
      - my-network
    restart: on-failure

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:80"
    networks:
      - my-network

  database:
    container_name: db-mysql
    image: mysql:latest
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tariff
      MYSQL_USER: iearul
      MYSQL_PASSWORD: root
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uiearul",
          "-proot"
        ]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - my-network

networks:
  my-network:
